# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: build py3.${{ matrix.python-version }} on ${{ matrix.platform || matrix.os }}
    environment: testing
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu , macos , windows]
        python-version: ['7', '8', '9', '10']
        include:
        - os: ubuntu
          platform: linux
        - os: windows
          ls: dir
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine setuptools wheel cibuildwheel
    - name: Build ${{ matrix.platform || matrix.os }} package 
      run: cibuildwheel --output-dir dist
      env:
        CIBW_BUILD: 'cp3${{ matrix.python-version }}-*'
        CIBW_SKIP: '*-win32'
        CIBW_PLATFORM: '${{ matrix.platform || matrix.os }}'
        # CIBW_MANYLINUX_X86_64_IMAGE: 'manylinux2014'
        # CIBW_MANYLINUX_I686_IMAGE: 'manylinux2014'
        CIBW_ARCHS_MACOS: 'x86_64 arm64'
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }} 
        repository_url: ${{ secrets.PYPI_URL }}
        skip_existing: true
